[package]
name = "imagecleanup"
version = "1.0.0"
authors = ["Manatsawin Hanmongkolchai <manatsawin+git@gmail.com>"]

[dependencies]
docker = { git = "https://github.com/whs/rust-docker.git" }
getopts = "0.2.14"
log = "0.3.3"
env_logger = "0.3.3"

[profile.release]
lto = true
